# Generated by Django 5.0.3 on 2024-05-17 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('text_processing', '0002_users_delete_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='full_name',
            new_name='username',
        ),
    ]
