# Generated by Django 5.0.3 on 2024-05-19 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('text_processing', '0004_article_users_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='vector',
            field=models.TextField(),
        ),
    ]
