# Generated by Django 5.0.3 on 2024-05-21 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('text_processing', '0005_alter_article_vector'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='true_labels',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
